var child = [
  { 'dupe': true, 'type': 4, 'name': 'driver', 'dir': 'c0', 'linked': 2, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/driver/', 'fetched': true, 'code': 404, 'len': 168, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'lib', 'dir': 'c1', 'linked': 2, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/lib/', 'fetched': true, 'code': 404, 'len': 165, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'receiver', 'dir': 'c2', 'linked': 2, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/receiver/', 'fetched': true, 'code': 404, 'len': 170, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'sender', 'dir': 'c3', 'linked': 2, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/sender/', 'fetched': true, 'code': 404, 'len': 168, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'transport', 'dir': 'c4', 'linked': 2, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/', 'fetched': true, 'code': 404, 'len': 171, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x5b2f35a3 },
  { 'dupe': true, 'type': 4, 'name': 'utils', 'dir': 'c5', 'linked': 2, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/utils/', 'fetched': true, 'code': 404, 'len': 167, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 32, 'name': 'C+f', 'dir': 'c6', 'linked': 2, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/C%2Bf', 'fetched': true, 'code': 404, 'len': 166, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff }
];
