var child = [
  { 'dupe': true, 'type': 4, 'name': 'cdk', 'dir': 'c0', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@angular/cdk/', 'fetched': true, 'code': 404, 'len': 173, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xe73cce76 },
  { 'dupe': true, 'type': 4, 'name': 'common', 'dir': 'c1', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@angular/common/', 'fetched': true, 'code': 404, 'len': 176, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xac91dad3 },
  { 'dupe': true, 'type': 4, 'name': 'core', 'dir': 'c2', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@angular/core/', 'fetched': true, 'code': 404, 'len': 174, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xac91dad3 },
  { 'dupe': true, 'type': 4, 'name': 'forms', 'dir': 'c3', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@angular/forms/', 'fetched': true, 'code': 404, 'len': 175, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xac91dad3 },
  { 'dupe': true, 'type': 4, 'name': 'material', 'dir': 'c4', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@angular/material/', 'fetched': true, 'code': 404, 'len': 178, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xe73cce76 },
  { 'dupe': true, 'type': 4, 'name': 'platform-browser', 'dir': 'c5', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@angular/platform-browser/', 'fetched': true, 'code': 404, 'len': 186, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xac91dad3 },
  { 'dupe': true, 'type': 4, 'name': 'router', 'dir': 'c7', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@angular/router/', 'fetched': true, 'code': 404, 'len': 176, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xac91dad3 }
];
