var child = [
  { 'dupe': true, 'type': 4, 'name': 'auth', 'dir': 'c0', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/auth/', 'fetched': true, 'code': 404, 'len': 160, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xe73ece68 },
  { 'dupe': true, 'type': 4, 'name': 'home', 'dir': 'c1', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/home/', 'fetched': true, 'code': 404, 'len': 160, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd6b0ad6d },
  { 'dupe': true, 'type': 4, 'name': 'list', 'dir': 'c2', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/list/', 'fetched': true, 'code': 404, 'len': 160, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xe73ece69 },
  { 'dupe': true, 'type': 4, 'name': 'material', 'dir': 'c3', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/material/', 'fetched': true, 'code': 404, 'len': 164, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'quest', 'dir': 'c4', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/quest/', 'fetched': true, 'code': 404, 'len': 161, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xef7ddefe },
  { 'dupe': true, 'type': 4, 'name': 'shared', 'dir': 'c5', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/shared/', 'fetched': true, 'code': 404, 'len': 162, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xef7ddefe },
  { 'dupe': true, 'type': 4, 'name': 'state', 'dir': 'c6', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/state/', 'fetched': true, 'code': 404, 'len': 161, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x3073e32e },
  { 'dupe': true, 'type': 4, 'name': 'themes', 'dir': 'c7', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/themes/', 'fetched': true, 'code': 404, 'len': 162, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd6b5ad52 },
  { 'dupe': true, 'type': 4, 'name': 'toolbar', 'dir': 'c8', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/src/app/toolbar/', 'fetched': true, 'code': 404, 'len': 163, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x94a32941 }
];
