var child = [
  { 'dupe': false, 'type': 4, 'name': '@angular', 'dir': 'c0', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@angular/', 'fetched': true, 'code': 404, 'len': 169, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x37c1f04a },
  { 'dupe': false, 'type': 4, 'name': '@ngrx', 'dir': 'c1', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/@ngrx/', 'fetched': true, 'code': 404, 'len': 166, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xf9fe7fca },
  { 'dupe': false, 'type': 4, 'name': 'ramda', 'dir': 'c2', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/ramda/', 'fetched': true, 'code': 404, 'len': 166, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x5291a52c },
  { 'dupe': false, 'type': 4, 'name': 'rxjs', 'dir': 'c3', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/rxjs/', 'fetched': true, 'code': 404, 'len': 165, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9d1db9c8 },
  { 'dupe': false, 'type': 4, 'name': 'ts-md5', 'dir': 'c4', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/ts-md5/', 'fetched': true, 'code': 404, 'len': 167, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x6b5fd6b0 },
  { 'dupe': true, 'type': 4, 'name': 'webpack', 'dir': 'c5', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/webpack/', 'fetched': true, 'code': 404, 'len': 168, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': false, 'type': 4, 'name': 'webpack-dev-server', 'dir': 'c6', 'linked': 2, 'url': 'http://10.182.95.138:4200/main.js/node_modules/webpack-dev-server/', 'fetched': true, 'code': 404, 'len': 179, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x8c6618c0 }
];
