var child = [
  { 'dupe': true, 'type': 4, 'name': 'lib', 'dir': 'c0', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/lib/', 'fetched': true, 'code': 404, 'len': 175, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xe6c34e52 },
  { 'dupe': true, 'type': 4, 'name': 'sender', 'dir': 'c1', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/sender/', 'fetched': true, 'code': 404, 'len': 178, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xbbaeeabe },
  { 'dupe': true, 'type': 32, 'name': 'eventsource', 'dir': 'c2', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/eventsource', 'fetched': true, 'code': 404, 'len': 182, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'htmlfile', 'dir': 'c3', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/htmlfile', 'fetched': true, 'code': 404, 'len': 179, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'iframe', 'dir': 'c4', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/iframe', 'fetched': true, 'code': 404, 'len': 177, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'jsonp-polling', 'dir': 'c5', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/jsonp-polling', 'fetched': true, 'code': 404, 'len': 184, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'websocket', 'dir': 'c6', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/websocket', 'fetched': true, 'code': 404, 'len': 180, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'xdr-polling', 'dir': 'c7', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/xdr-polling', 'fetched': true, 'code': 404, 'len': 182, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'xdr-streaming', 'dir': 'c8', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/xdr-streaming', 'fetched': true, 'code': 404, 'len': 184, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'xhr-polling', 'dir': 'c9', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/xhr-polling', 'fetched': true, 'code': 404, 'len': 182, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'xhr-streaming', 'dir': 'c10', 'linked': 1, 'url': 'http://10.182.95.138:4200/webpack-dev-server.js/transport/xhr-streaming', 'fetched': true, 'code': 404, 'len': 184, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff }
];
