var child = [
  { 'dupe': true, 'type': 4, 'name': 'driver', 'dir': 'c0', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/driver/', 'fetched': true, 'code': 404, 'len': 184, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'lib', 'dir': 'c1', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/lib/', 'fetched': true, 'code': 404, 'len': 181, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'receiver', 'dir': 'c2', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/receiver/', 'fetched': true, 'code': 404, 'len': 186, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': 'sender', 'dir': 'c3', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/sender/', 'fetched': true, 'code': 404, 'len': 184, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': false, 'type': 4, 'name': 'transport', 'dir': 'c4', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/transport/', 'fetched': true, 'code': 404, 'len': 187, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x5b2f35a3 },
  { 'dupe': true, 'type': 4, 'name': 'utils', 'dir': 'c5', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/', 'fetched': true, 'code': 404, 'len': 183, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 32, 'name': 'E.fx.off', 'dir': 'c6', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/E.fx.off', 'fetched': true, 'code': 404, 'len': 185, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff }
];
