var child = [
  { 'dupe': false, 'type': 4, 'name': 'driver', 'dir': 'c0', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/driver/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'lib', 'dir': 'c1', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/lib/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'receiver', 'dir': 'c2', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/receiver/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'sender', 'dir': 'c3', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/sender/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'transport', 'dir': 'c4', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/transport/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'utils', 'dir': 'c5', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'E.fx.off', 'dir': 'c6', 'linked': 2, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/E.fx.off', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
