var child = [
  { 'dupe': true, 'type': 32, 'name': 'browser', 'dir': 'c0', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/browser', 'fetched': true, 'code': 404, 'len': 190, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'escape', 'dir': 'c1', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/escape', 'fetched': true, 'code': 404, 'len': 189, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'event', 'dir': 'c2', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/event', 'fetched': true, 'code': 404, 'len': 188, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'iframe', 'dir': 'c3', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/iframe', 'fetched': true, 'code': 404, 'len': 189, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'log', 'dir': 'c4', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/log', 'fetched': true, 'code': 404, 'len': 186, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'object', 'dir': 'c5', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/object', 'fetched': true, 'code': 404, 'len': 189, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'random', 'dir': 'c6', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/random', 'fetched': true, 'code': 404, 'len': 189, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'transport', 'dir': 'c7', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/transport', 'fetched': true, 'code': 404, 'len': 192, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff },
  { 'dupe': true, 'type': 32, 'name': 'url', 'dir': 'c8', 'linked': 1, 'url': 'http://10.182.95.138:4200/__webpack_dev_server__/live.bundle.js/utils/url', 'fetched': true, 'code': 404, 'len': 186, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffdfffff }
];
